[package]
name = "e314-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9"
colored = "3.0.0"
regex = "1.11.1"
serde_json = "1.0.140"
chrono = "0.4.41"


